services:
  - type: web
    name: mrat-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 5432

  - type: web
    name: mrat-client
    env: node
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: VITE_API_URL
        value: https://mrat-server.onrender.com

databases:
  - name: mrat-timescale
    databaseName: mrat
    user: mrat_user
    plan: free 