services:
  - type: web
    name: mrat-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://mrat-backend.onrender.com/api
      - key: NODE_VERSION
        value: 18.17.0

  - type: web
    name: mrat-backend
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:server
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
      - key: NODE_VERSION
        value: 18.17.0 