services:
  - type: web
    name: mrat-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://mrat-backend.onrender.com/api
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production

  - type: web
    name: mrat-backend
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: node dist/server/index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://joelsaarelainen:cbHEnuaylnWoHmJQ@cluster0.tcglbjj.mongodb.net/mrat?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 3001
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production 