services:
  - type: web
    name: mrat-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://mrat-backend.onrender.com/api
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production

  - type: web
    name: mrat-backend
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:server
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://jopes:jopes@cluster0.mongodb.net/mrat?retryWrites=true&w=majority
      - key: PORT
        value: 5000
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production 